name: dvault
description: A sample command-line application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  async: 2.8.2 
  dcli: 1.7.1
  encrypt: ^5.0.1
  meta: ^1.0.0
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4

dependency_overrides:
  dcli:
    path: ../dcli

executables:
  dvault: