name: dvault
version: 3.0.0
publish_to: https://beta.onepub.dev/api/apsdavuhno/
description: A sample command-line application.
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: 2.8.2
  dcli: 1.21.12
  dcli_core: 1.21.12
  encrypt: ^5.0.1
  meta: ^1.0.0
  path: ^1.0.0
  pointycastle: ^3.0.0
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.14.4
executables: 
  dvault: 
