name: dvault
description: A sample command-line application.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: 2.8.2
  dcli: 1.14.3
  encrypt: ^5.0.1
  meta: ^1.0.0
  pointycastle: ^3.0.0
dev_dependencies: 
  lint: ^1.0.0
  test: ^1.14.4
dependency_overrides: 
  dcli: 
    path: ../dcli/dcli
executables: 
  dvault: 
